export const REVERSE_BIRTH_TIME_SELECT_FIELDS = [
  {
    id: 'bodyBuild',
    label: '体型气质',
    helper: '如果知道大概体型、气质或别人常给你的印象，可以选最接近的一项。',
    options: [
      '未选择',
      '偏瘦灵活',
      '匀称平稳',
      '骨架明显或偏壮',
      '圆润松弛',
      '五官秀气',
      '肤色偏白或清冷',
      '少年显小成熟后更显气场',
      '气质强势显眼',
      '少年和成年差异明显',
    ],
  },
  {
    id: 'personalityStyle',
    label: '性格节奏',
    helper: '选择更像自己的整体状态，不需要特别准确。',
    options: [
      '未选择',
      '外向主动',
      '慢热谨慎',
      '敏感多思',
      '务实稳定',
      '理性克制',
      '情绪起伏明显',
      '要强不服输',
      '随和好说话',
      '行动快但容易急',
      '想很多再行动',
    ],
  },
  {
    id: 'familyAtmosphere',
    label: '成长氛围',
    helper: '回忆小时候的家庭感受即可。',
    options: [
      '未选择',
      '整体稳定',
      '要求严格',
      '照顾较多',
      '父母比较强势',
      '变动较多',
      '关系疏离',
      '和母亲更亲',
      '和父亲更亲',
      '家里规矩多',
      '自己小时候更早独立',
    ],
  },
  {
    id: 'caregiverPattern',
    label: '童年主要照料者',
    helper: '看小时候长期是谁带你、陪你更多。',
    options: [
      '未选择',
      '主要由父母亲自带大',
      '更多由母亲照顾',
      '更多由父亲照顾',
      '长期跟祖辈生活',
      '有寄宿或长期离家经历',
      '经常由亲友帮忙照看',
    ],
  },
  {
    id: 'educationLevel',
    label: '学历和学业路径',
    helper: '按最高学历或整体学业路径选择，哪怕只是大概也可以。',
    options: [
      '未选择',
      '中学及以下',
      '大专',
      '普通本科',
      '重点本科或名校路径',
      '本科以上',
      '读书一路较顺',
      '重要考试起伏明显',
      '考研考公考编经历明显',
      '有换专业或复读经历',
      '早早工作或中途离校',
      '学历一般但技能路线清晰',
    ],
  },
  {
    id: 'careerPattern',
    label: '工作状态',
    helper: '如果已经工作，可以选更像自己的状态；暂时不确定可以留空。',
    options: [
      '未选择',
      '比较稳定',
      '变化较多',
      '自己主导性强',
      '容易受环境影响',
      '适合单打独斗',
      '适合在体系内发展',
      '早期反复试错',
      '越往后越稳定',
      '贵人帮助明显',
      '靠专业能力吃饭',
    ],
  },
  {
    id: 'socialStyle',
    label: '社交和表达',
    helper: '选更像你平时和人相处、说话表达的状态。',
    options: [
      '未选择',
      '话不多但观察多',
      '表达直接',
      '很会照顾气氛',
      '边界感强',
      '熟了以后很能聊',
      '容易憋着不说',
      '容易被看作靠谱',
      '容易被看作有距离感',
    ],
  },
  {
    id: 'relationshipTiming',
    label: '恋爱开始节奏',
    helper: '如果感情开始偏早或偏晚，通常也能提供一些反推线索。',
    options: [
      '未选择',
      '学生时代就有明显感情经历',
      '工作后才开始认真恋爱',
      '恋爱偏晚',
      '桃花不少但不稳定',
      '遇到喜欢的人不多',
      '常有暧昧但难落地',
      '关系推进快',
    ],
  },
  {
    id: 'earlyRomanceStatus',
    label: '早恋和情感启蒙',
    helper: '如果知道自己情感启蒙偏早还是偏晚，也可以补一条。',
    options: [
      '未选择',
      '中学阶段就有明显感情经历',
      '大学阶段感情经历更明显',
      '工作后才真正开始',
      '身边桃花不少但自己谨慎',
      '很少真正进入关系',
      '容易暗恋或单向投入',
    ],
  },
  {
    id: 'marriageParentingStatus',
    label: '婚育状态',
    helper: '如果不方便细说，也可以只选最接近的一项。',
    options: [
      '未选择',
      '未婚未育',
      '有稳定对象',
      '已婚',
      '已育',
      '感情经历较少',
      '感情经历不止一段',
      '婚育节奏偏晚',
    ],
  },
  {
    id: 'healthPattern',
    label: '身体体感',
    helper: '选择最常见的倾向，不需要医学判断。',
    options: [
      '未选择',
      '精力较稳',
      '容易疲惫',
      '睡眠波动大',
      '情绪容易影响身体',
      '肠胃偏敏感',
      '容易上火',
      '偏寒或手脚凉',
      '肩颈头痛较多',
      '容易过敏或皮肤敏感',
      '恢复慢但能扛',
    ],
  },
  {
    id: 'schedulePattern',
    label: '作息偏向',
    helper: '看你长期更像早睡早起还是夜里更有精神。',
    options: [
      '未选择',
      '早睡早起型',
      '晚睡晚起型',
      '晚上更有精神',
      '白天状态更稳',
      '作息经常被工作打乱',
      '睡眠浅容易醒',
      '熬夜后恢复慢',
    ],
  },
  {
    id: 'mobilityPattern',
    label: '居住和变动',
    helper: '选更像你整体人生节奏的迁移状态。',
    options: [
      '未选择',
      '长期在一个地方',
      '学生时代有明显搬迁',
      '工作后换过城市',
      '离家发展比较早',
      '经常出差或跑动',
      '出国或长期异地经历',
      '人生阶段变化多',
    ],
  },
  {
    id: 'leaveHometownStatus',
    label: '离乡发展情况',
    helper: '是否离开出生地长期发展，通常也有参考价值。',
    options: [
      '未选择',
      '基本一直在老家',
      '上学后离乡',
      '工作后离乡',
      '长期异地发展',
      '多地来回切换',
      '有出国或长期外地经历',
      '离乡后发展更明显',
    ],
  },
] as const;

export const REVERSE_BIRTH_TIME_TEXT_FIELDS = [
  {
    id: 'parentsMarriageNotes',
    label: '父母关系状态',
    helper: '简单填写即可，例如关系稳定、常年争吵、早年离异、父亲常年不在家。',
    placeholder: '例如：关系稳定；常年争吵；早年离异；主要由母亲照顾。',
    inputType: 'text',
  },
  {
    id: 'siblingNotes',
    label: '兄弟姐妹情况',
    helper: '直接简单填写即可，例如独生、一姐一弟、两个妹妹。',
    placeholder: '例如：独生；一姐一弟；两个妹妹。',
    inputType: 'text',
  },
  {
    id: 'familyOrderNotes',
    label: '家中角色',
    helper: '直接填写你在家里更像什么位置，例如老大、常承担责任、被照顾较多。',
    placeholder: '例如：家里老大；常承担责任；容易夹在中间协调。',
    inputType: 'text',
  },
  {
    id: 'workSystemNotes',
    label: '工作体制和路径',
    helper: '简单填写工作环境或路径，例如在编、大厂、创业、频繁换行业。',
    placeholder: '例如：在编；大厂几年后创业；长期民企；跨行业换过两次。',
    inputType: 'text',
  },
  {
    id: 'careerTypeNotes',
    label: '职业类型',
    helper: '直接填写更像你的工作类型，例如技术岗、销售、设计、教师、管理岗。',
    placeholder: '例如：技术岗；设计转运营；教师；销售后期带团队。',
    inputType: 'text',
  },
  {
    id: 'keyYearsNotes',
    label: '关键年份',
    helper: '只写年份和事件，越短越好，例如搬家、升学、毕业、换城市、结婚等。',
    placeholder: '例如：2012 搬家，2018 毕业，2020 换城市。',
    inputType: 'text',
  },
  {
    id: 'livingPatternNotes',
    label: '居住状态',
    helper: '简单填写长期居住状态，例如长期和父母同住、独居、住宿舍、搬家频繁。',
    placeholder: '例如：长期和父母同住；工作后常独居；租房搬动较多。',
    inputType: 'text',
  },
  {
    id: 'relationshipPatternNotes',
    label: '感情状态',
    helper: '直接填写最像你的感情模式，例如慢热、恋爱少但认真、容易反复、重稳定。',
    placeholder: '例如：慢热保守；恋爱少但很认真；关系起伏明显；更重精神交流。',
    inputType: 'text',
  },
  {
    id: 'extraClueNotes',
    label: '其他补充线索',
    helper: '如果还有特别明显的经历或状态，用几句话写最关键的就行，不用写成长文。',
    placeholder: '例如：小时候跟母亲更亲，恋爱偏晚，睡眠浅，肠胃偏敏感。',
    inputType: 'textarea',
    rows: 3,
  },
] as const;

type ReverseBirthTimeSelectFieldId = (typeof REVERSE_BIRTH_TIME_SELECT_FIELDS)[number]['id'];
type ReverseBirthTimeTextFieldId = (typeof REVERSE_BIRTH_TIME_TEXT_FIELDS)[number]['id'];

export type ReverseBirthTimeFormData = Record<ReverseBirthTimeSelectFieldId, string> &
  Record<ReverseBirthTimeTextFieldId, string>;

export const DEFAULT_REVERSE_BIRTH_TIME_FORM_DATA: ReverseBirthTimeFormData = {
  bodyBuild: '未选择',
  personalityStyle: '未选择',
  familyAtmosphere: '未选择',
  caregiverPattern: '未选择',
  educationLevel: '未选择',
  careerPattern: '未选择',
  socialStyle: '未选择',
  relationshipTiming: '未选择',
  earlyRomanceStatus: '未选择',
  marriageParentingStatus: '未选择',
  healthPattern: '未选择',
  schedulePattern: '未选择',
  mobilityPattern: '未选择',
  leaveHometownStatus: '未选择',
  parentsMarriageNotes: '',
  siblingNotes: '',
  familyOrderNotes: '',
  workSystemNotes: '',
  careerTypeNotes: '',
  keyYearsNotes: '',
  livingPatternNotes: '',
  relationshipPatternNotes: '',
  extraClueNotes: '',
};
